<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 25/07/2020
 * Time: 19:58
 */

namespace Administration\Controller;


use Administration\Controller\Base\BaseController;
use Doctrine\ORM\EntityManager;
use Laminas\Mvc\Controller\AbstractActionController;

class IndexController extends AbstractActionController
{

    protected $entityManager;

    public function __construct(EntityManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

}