<?php
$this->headTitle('Sign in');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email address',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Password',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<!-- Main container start -->
<section id="main-container">
    <div class="container">
        <?php if ($isLoginError): ?>
        <div class="row">
            <div class="alert alert-warning" role="alert">
                Incorrect login and/or password.
                <a href="<?= $this->url('forum/sign', ['action'=>'forgottenPassword','id_forum'=>\User\Module::getForumId()]) ?>">Forgot password?</a>
            </div>
        </div>
        <?php endif; ?>

        <div class="row">
            <div class="col-md-7">
                <?= $this->form()->opentag($this->form); ?>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label><?= $this->formLabel($form->get('email')); ?></label>
                                <?= $this->formElement($form->get('email')); ?>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label><?= $this->formLabel($form->get('password')); ?></label>
                                <?= $this->formElement($form->get('password')); ?>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="checkbox">
                                <label>
                                    <?= $this->formElement($form->get('remember_me')); ?> Remember me
                                </label>
                            </div>
                        </div>
                    </div>
                    <?= $this->formElement($form->get('redirect_url')); ?>
                    <?= $this->formElement($form->get('csrf')) ?>
                    <div class="text-right"><br>
                        <button class="btn btn-primary solid blank" type="submit">Send Message</button>
                    </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <!--/ container end -->
</section>