<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 16/07/2020
 * Time: 19:27
 */
?>

<?= $form = $this->form()->openTag($this->form); ?>

<div class="form-group">
    <?= $this->formLabel($this->form->get('description')); ?>
    <?= $this->formElement($this->form->get('description')); ?>
    <?= $this->formElementErrors($this->form->get('description')); ?>
</div>

<div class="form-group">
    <?= $this->formLabel($this->form->get('signature')); ?>
    <?= $this->formElement($this->form->get('signature')); ?>
    <?= $this->formElementErrors($this->form->get('signature')); ?>
</div>

<div class="form-group">
    <?= $this->formElement($this->form->get('submit')); ?>
</div>

<div class="form-group">
    <?= $this->formElement($this->form->get('csrf')); ?>
</div>

<?= $this->form()->closeTag(); ?>

