<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 09/08/2020
 * Time: 08:44
 */
?>

<h2>Notre annuaire</h2>
<div class="row">
    <?php foreach($this->fora as $forum): ?>
    <div class="col-lg-3">
        <div class="card mb-3">
            <h3 class="card-header"><?= $forum->getName(); ?></h3>
            <?php if( $forum->getDescription() ): ?>
                <div class="card-body">
                    <h5 class="card-title">Synopsis</h5>
                    <h6 class="card-subtitle text-muted"><?= $forum->getDescription(); ?></h6>
                </div>
            <?php endif; ?>
            <?php if($forum->getElements()): ?>
            <img style="height: 200px; width: 100%; display: block;" src="<?= $forum->getElements()->getHeaderImage(); ?>" alt="<?= $forum->getName(); ?>">
            <?php endif; ?>
            <div class="card-body">
                <p class="card-text"></p>
            </div>
            <div class="card-body">
                <a href="<?= $this->url('forum/forum', ['id_forum'=>$forum->getId()]); ?>" class="card-link">Visiter</a>
            </div>
            <div class="card-footer text-muted">
                Admin: Faith Lehane
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
