<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 28/07/2020
 * Time: 19:46
 */


$this->headTitle('Edit Permission');


$form->get('attribute')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter data'
    ]);

$form->get('value')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter data'
]);

$form->get('key')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter data'
]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');

$form->prepare();
?>

<h1>Edit Permission</h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('attribute')); ?>
            <?= $this->formElement($form->get('attribute')); ?>
            <?= $this->formElementErrors($form->get('attribute')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('value')); ?>
            <?= $this->formElement($form->get('value')); ?>
            <?= $this->formElementErrors($form->get('value')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('key')); ?>
            <?= $this->formElement($form->get('key')); ?>
            <?= $this->formElementErrors($form->get('key')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
