<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 11/07/2020
 * Time: 11:22
 */
?>

<?= $form = $this->form()->openTag($this->form); ?>

<div class="form-group">
    <?= $this->formLabel($this->form->get('title')); ?>
    <?= $this->formElement($this->form->get('title')); ?>
    <?= $this->formElementErrors($this->form->get('title')); ?>
</div>

<div class="form-group">
    <?= $this->formLabel($this->form->get('catchphrase')); ?>
    <?= $this->formElement($this->form->get('catchphrase')); ?>
    <?= $this->formElementErrors($this->form->get('catchphrase')); ?>
</div>


<h2>
    Post initial
</h2>

<?php if($this->template): ?>
    <?php foreach( json_decode($this->template->getVariables()) as $key => $template ): ?>
    <div class="row">
        <label for="custom_<?= $template; ?>"><?= $template ?></label>
        <input type="text" id="custom_<?= $template ?>" name="custom[<?= $template ?>]" placeholder="<?= $template ?>">
    </div>
    <?php endforeach;?>

<?php else: ?>
    <div class="row">
        <label for="normal_post">Premier post</label>
        <textarea id="normal_post" name="normal_post"></textarea>
    </div>
<?php endif; ?>

<div class="form-group">
    <?= $this->formElement($this->form->get('submit')); ?>
</div>

<div class="form-group">
    <?= $this->formElement($this->form->get('csrf')); ?>
</div>

<?= $this->form()->closeTag(); ?>
