<div class="x_content">
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">
                <p class="text-muted font-13 m-b-30">
                    Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.
                </p>

                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Pseudo</th>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Email</th>
                        <th>Date d'inscription</th>
                        <th>Posts</th>
                        <th>Status</th>
                        <th>Role</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($this->users as $user): ?>
                    <tr>
                        <td><?= $user->getAlias(); ?></td>
                        <td><?= $user->getName(); ?></td>
                        <td><?= $user->getFirstName(); ?></td>
                        <td><?= $user->getEmail(); ?></td>
                        <td><?= $user->getDateCreated()->format('d/m/Y'); ?></td>
                        <td><?= $user->countPosts(); ?></td>
                        <td><?= $user->getStatus(); ?></td>
                        <td>Membre</td>
                        <td>
                            <a href="<?= $this->url('admin/user', ['action'=>'edit', 'id_forum'=>\User\Module::getForumId(), 'id'=>$user->getId()]); ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                            <a href="<?= $this->url('admin/user', ['action'=>'password', 'id_forum'=>\User\Module::getForumId(), 'id'=>$user->getId()]); ?>"><i class="fas fa-key"></i></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

                <a class="btn btn-success" href="<?= $this->url('admin/user', ['action'=>'new', 'id_forum'=>\User\Module::getForumId()]); ?>">Créer un utilisateur</a>


            </div>
        </div>
    </div>
</div>