<?php
$this->headTitle('View Permission');

?>


<h1>View Permission</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($permission->getId()) ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?= $this->escapeHtml($permission->getName()) ?></th>
            </tr>
            <tr>
                <th>Description:</th>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($permission->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>