<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 11/07/2020
 * Time: 09:25
 */

namespace Application\Controller;


use Application\Controller\Base\BaseController;
use Application\Entity\ForumSubject;
use Doctrine\ORM\EntityManager;
use Laminas\Mvc\Controller\AbstractActionController;
use Laminas\View\Model\ViewModel;

/**
 * Class SubjectController
 * @package Application\Controller
 */
class SubjectController extends AbstractActionController
{
    /**
     * @var EntityManager
     */
    protected $entityManager;

    /**
     * SubjectController constructor.
     * @param EntityManager $entityManager
     */
    public function __construct(EntityManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }


    /**
     * @return ViewModel
     */
    public function indexAction():ViewModel
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    public function viewAction():ViewModel
    {
        $idSubject = (int) $this->params()->fromRoute('id_subject', -1);

        $subject = $this->entityManager->getRepository(ForumSubject::class)->findOneBy([
            'id'=>$idSubject
        ]);

        if(!$subject){
            $this->getResponse()->setStatusCode(404);
        }

        return new ViewModel([
            "subject"=>$subject
        ]);
    }

}