<?php
$this->headTitle('Edit Subject');


$this->form->get('title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ]);

$this->form->get('catchphrase')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'John Doe'
    ]);

$this->form->get('category_id')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe'
]);

$this->form->get('type')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe'
]);

$this->form->get('status')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe'
]);

$this->form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');

$this->form->prepare();
?>

<h1>New Subject</h1>

<div class="row">
    <div class="col-md-6">
        <?= $form = $this->form()->openTag($this->form); ?>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('title')); ?>
            <?= $this->formElement($this->form->get('title')); ?>
            <?= $this->formElementErrors($this->form->get('title')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('catchphrase')); ?>
            <?= $this->formElement($this->form->get('catchphrase')); ?>
            <?= $this->formElementErrors($this->form->get('catchphrase')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('category_id')); ?>
            <?= $this->formElement($this->form->get('category_id')); ?>
            <?= $this->formElementErrors($this->form->get('category_id')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('type')); ?>
            <?= $this->formElement($this->form->get('type')); ?>
            <?= $this->formElementErrors($this->form->get('type')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('status')); ?>
            <?= $this->formElement($this->form->get('status')); ?>
            <?= $this->formElementErrors($this->form->get('status')); ?>
        </div>

        <div class="form-group">
            <?= $this->formElement($this->form->get('submit')); ?>
        </div>

        <div class="form-group">
            <?= $this->formElement($this->form->get('csrf')); ?>
        </div>

        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

